branches:
  except:
  - release

sudo: required

matrix:
  include:
    - os: osx
      env: BUILD_NAME=macosx
      compiler: clang
      language: cpp
      osx_image: xcode7.3
    - os: osx
      env: BUILD_NAME=ios
      compiler: clang
      language: cpp
      osx_image: xcode7.3
    - os: linux
      env: BUILD_NAME=debian
      compiler: gcc
      language: cpp
      dist: trusty
    - os: linux
      env: BUILD_NAME=ubuntu
      compiler: gcc
      language: cpp
      dist: trusty
    - os: linux
      env: BUILD_NAME=raspberry_pi
      compiler: gcc
      language: cpp
      dist: trusty
    - env: BUILD_NAME=android
      language: android


android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
#    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository


env:
  global:
  #encrypted PRORAB_GIT_ACCESS_TOKEN for publishing to github-based repos
  - secure: "gfyfvYP5Gv9NByD4K3p6h7fvXbwN2rno3UfIsUtdWsnZOn35dpntXkYxXLdXTnAOkdcy0H9oy1lt5jNYGvY0tagmrB0rtmVHrn0Jbe3DHIZqYUozCIH4m7WhamGZkQAzBKogahw4+5tLNxgKxn1rimfL5vHg+m8D1zRf+kgtiUEO3pkvkXwZJQQ0QDAgarHDGdMrlDiFukV4I9FW9ysKWgUYa5psdqm7awltmitRy7ekR87obTU1pUb274gfSk2BGO0QmExfLYgczD+xl1xlQDcSH6xNigkGzsgOnlJMnv8O+OLkpVXgJCD6gGsIHjZOrG8jMnF9x3iFQ/Il3dJFzL199t9d0J0Sm98kEKRv+dLWNAvURo9lzSFAk9rPNkwiCrdJDGL+IsRccc9c4akCV6SWGyUgHiIh5JxFfs+ec7FdqqEt53zNcOS1b5PN6AD7iYVy6i+1ZANMPkvc/srtZdhwpVIPuePE7cEyJky+Z6DionMwgGWK10aZovnL2amf4P7wJQ48gol3mie69EekZ4fTeXFyyqPJnrfSZnzD5480noCLjXlo4z3J89dAGFYJBgvekl8F8ZuVRFjGk4kTCyjmA1d7gfT506hKvOvNtXdtEn8WlH5q+nkR0EfQQfSevlLZLA51xTxwFCIVNekmmRjGamZU6hl7ClkwUq+jtO0="
  - MYCI_GIT_USERNAME=igagis
  - MYCI_GIT_ACCESS_TOKEN=$PRORAB_GIT_ACCESS_TOKEN
  - USE_ANDROID_NDK_VERSION=15c
  - linuxDependencies="lintian debhelper prorab prorab-extra myci doxygen libutki-dev libpapki-dev libunikod-dev"


before_install:
- if [ "$BUILD_NAME" == "macosx" ]; then
    rvm install ruby-2.3.3 &&
    rvm use ruby-2.3.3 &&
    
    brew update > /dev/null &&
    brew tap igagis/tap &&
    brew update > /dev/null &&
    brew install prorab prorab-extra myci libutki libpapki libunikod;
  fi
- if [ "$BUILD_NAME" == "ios" ]; then
    rvm install ruby-2.3.3 &&
    rvm use ruby-2.3.3 &&
    
    brew update > /dev/null &&
    brew tap igagis/tap &&
    brew update > /dev/null &&
    brew install myci &&
    
    sudo gem install cocoapods &&
    pod repo add --silent igagis https://$PRORAB_GIT_USERNAME:$PRORAB_GIT_ACCESS_TOKEN@github.com/igagis/cocoapods-repo.git &&
    pod install --project-directory=ios;
  fi
- if [ "$BUILD_NAME" == "android" ]; then
    echo "deb [arch=amd64] https://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq myci;
  fi
- if [ "$BUILD_NAME" == "debian" ]; then
    echo "deb [arch=amd64] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq sbuild prorab prorab-extra myci debhelper &&
    sudo sbuild-adduser $LOGNAME &&
    echo lQHYBFfZDkYBBACyRm0LCwK/9rSzqSJyEBihVNA61meWp9MVjn3EBPp6MV1/mjZ80LPJ6ecYX6VMu861a5yQLnlA9krUxuHxjnsEYvMQiz0zHapp8Zqu0FIvcU1IWZV7Eio5Lej7QFeHFmtPlrSqT152lVUmQFW9ZCtWOOM1KnKBhoWWLf9z7LnwSwARAQABAAP/SWyYHKQ8TbPeWOCgPzpB6rBz0sfbgkE8vvQg+ErUnt8WEygAqQeMBO1BMNizzBbN3AqmQPvjFM5bo6cGB+cW4tbmWVtp8wMGVm8dobiZP3p1YLtvrweX3gYo1P4km8B7JkeJ0oyGa1k4yP5m4+o7t97EanKLFTFCbJvV/txT+YECAMLhKBMGJBqa8766tsyXbKaHQKvUDwlVCltAbeRb/V7cnIEuf/bn5DcN2O3yhN35OX5EvCeJxtCSBDh9HkQfK0cCAOowGoepffgLuuOfnpNU3GcHU9lNsLUnYJ17Oa38z1JGjggrUvQ5V6UbH0YY14vQXbrOVn+YE9Job9UCnM6DzN0B/19ZoYzH9anOf+nmTM56Rrk8itQXhN/gpI22EZ9n8koELvYrHj3iUgPJ+BOCKTP3E9brojEC048pK58GFJkr+/qjqbRgU2J1aWxkIFNpZ25lciAoU2J1aWxkIEJ1aWxkIERlcGVuZGVuY3kgQXJjaGl2ZSBLZXkpIDxidWlsZGQtdG9vbHMtZGV2ZWxAbGlzdHMuYWxpb3RoLmRlYmlhbi5vcmc+iLgEEwECACIFAlfZDkYCGy8GCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJELG4iKvjYvQgomAEAJzhmqIVxIU3+ROL0B8Q2Iv1gWRe6X17J1UQPYIGkRYcZWYUllWjmk32snT5Yv+x2TMVojD0JCCgltU0JBvydovItd+g6H+C8I/bhoq5twC9CIYGKmhDInxwCdHG8yU7AVdEopf38VsEC+3Hazh4V5sPldHMo9Lx6u5uXiil5qKi | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.sec > /dev/null &&
    echo mI0EV9kORgEEALJGbQsLAr/2tLOpInIQGKFU0DrWZ5an0xWOfcQE+noxXX+aNnzQs8np5xhfpUy7zrVrnJAueUD2StTG4fGOewRi8xCLPTMdqmnxmq7QUi9xTUhZlXsSKjkt6PtAV4cWa0+WtKpPXnaVVSZAVb1kK1Y44zUqcoGGhZYt/3PsufBLABEBAAG0YFNidWlsZCBTaWduZXIgKFNidWlsZCBCdWlsZCBEZXBlbmRlbmN5IEFyY2hpdmUgS2V5KSA8YnVpbGRkLXRvb2xzLWRldmVsQGxpc3RzLmFsaW90aC5kZWJpYW4ub3JnPoi4BBMBAgAiBQJX2Q5GAhsvBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRCxuIir42L0IKJgBACc4ZqiFcSFN/kTi9AfENiL9YFkXul9eydVED2CBpEWHGVmFJZVo5pN9rJ0+WL/sdkzFaIw9CQgoJbVNCQb8naLyLXfoOh/gvCP24aKubcAvQiGBipoQyJ8cAnRxvMlOwFXRKKX9/FbBAvtx2s4eFebD5XRzKPS8erubl4opeaiog== | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.pub > /dev/null &&
    sudo sbuild-createchroot --include=gnupg1,dirmngr,build-essential stretch /srv/chroot/deb-amd64 http://httpredir.debian.org/debian &&
    echo "deb [trusted=yes] http://dl.bintray.com/igagis/deb unstable main" | sudo tee /srv/chroot/deb-amd64/etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo chroot /srv/chroot/deb-amd64 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo chroot /srv/chroot/deb-amd64 ln -s /usr/bin/gpg1 /usr/bin/gpg;
  fi
- if [ "$BUILD_NAME" == "ubuntu" ]; then
    echo "deb [arch=amd64] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq sbuild prorab prorab-extra myci debhelper &&
    sudo sbuild-adduser $LOGNAME &&
    echo lQHYBFfZDkYBBACyRm0LCwK/9rSzqSJyEBihVNA61meWp9MVjn3EBPp6MV1/mjZ80LPJ6ecYX6VMu861a5yQLnlA9krUxuHxjnsEYvMQiz0zHapp8Zqu0FIvcU1IWZV7Eio5Lej7QFeHFmtPlrSqT152lVUmQFW9ZCtWOOM1KnKBhoWWLf9z7LnwSwARAQABAAP/SWyYHKQ8TbPeWOCgPzpB6rBz0sfbgkE8vvQg+ErUnt8WEygAqQeMBO1BMNizzBbN3AqmQPvjFM5bo6cGB+cW4tbmWVtp8wMGVm8dobiZP3p1YLtvrweX3gYo1P4km8B7JkeJ0oyGa1k4yP5m4+o7t97EanKLFTFCbJvV/txT+YECAMLhKBMGJBqa8766tsyXbKaHQKvUDwlVCltAbeRb/V7cnIEuf/bn5DcN2O3yhN35OX5EvCeJxtCSBDh9HkQfK0cCAOowGoepffgLuuOfnpNU3GcHU9lNsLUnYJ17Oa38z1JGjggrUvQ5V6UbH0YY14vQXbrOVn+YE9Job9UCnM6DzN0B/19ZoYzH9anOf+nmTM56Rrk8itQXhN/gpI22EZ9n8koELvYrHj3iUgPJ+BOCKTP3E9brojEC048pK58GFJkr+/qjqbRgU2J1aWxkIFNpZ25lciAoU2J1aWxkIEJ1aWxkIERlcGVuZGVuY3kgQXJjaGl2ZSBLZXkpIDxidWlsZGQtdG9vbHMtZGV2ZWxAbGlzdHMuYWxpb3RoLmRlYmlhbi5vcmc+iLgEEwECACIFAlfZDkYCGy8GCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJELG4iKvjYvQgomAEAJzhmqIVxIU3+ROL0B8Q2Iv1gWRe6X17J1UQPYIGkRYcZWYUllWjmk32snT5Yv+x2TMVojD0JCCgltU0JBvydovItd+g6H+C8I/bhoq5twC9CIYGKmhDInxwCdHG8yU7AVdEopf38VsEC+3Hazh4V5sPldHMo9Lx6u5uXiil5qKi | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.sec > /dev/null &&
    echo mI0EV9kORgEEALJGbQsLAr/2tLOpInIQGKFU0DrWZ5an0xWOfcQE+noxXX+aNnzQs8np5xhfpUy7zrVrnJAueUD2StTG4fGOewRi8xCLPTMdqmnxmq7QUi9xTUhZlXsSKjkt6PtAV4cWa0+WtKpPXnaVVSZAVb1kK1Y44zUqcoGGhZYt/3PsufBLABEBAAG0YFNidWlsZCBTaWduZXIgKFNidWlsZCBCdWlsZCBEZXBlbmRlbmN5IEFyY2hpdmUgS2V5KSA8YnVpbGRkLXRvb2xzLWRldmVsQGxpc3RzLmFsaW90aC5kZWJpYW4ub3JnPoi4BBMBAgAiBQJX2Q5GAhsvBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRCxuIir42L0IKJgBACc4ZqiFcSFN/kTi9AfENiL9YFkXul9eydVED2CBpEWHGVmFJZVo5pN9rJ0+WL/sdkzFaIw9CQgoJbVNCQb8naLyLXfoOh/gvCP24aKubcAvQiGBipoQyJ8cAnRxvMlOwFXRKKX9/FbBAvtx2s4eFebD5XRzKPS8erubl4opeaiog== | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.pub > /dev/null &&
    sudo sbuild-createchroot --include=gnupg,dirmngr,build-essential --components=main,universe xenial /srv/chroot/ubu-amd64 http://archive.ubuntu.com/ubuntu/ &&
    echo "deb [trusted=yes] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /srv/chroot/ubu-amd64/etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo chroot /srv/chroot/ubu-amd64 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61;
  fi
- if [ "$BUILD_NAME" == "raspberry_pi" ]; then
    echo "deb [arch=amd64] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq prorab prorab-extra myci;
    sudo myci-make-raspberry-chroot.sh /srv/chroot/rasp-armhf &&
    echo "deb [arch=armhf] http://dl.bintray.com/igagis/rasp unstable main" | sudo tee /srv/chroot/rasp-armhf/etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo chroot /srv/chroot/rasp-armhf apt-get update &&
    sudo chroot /srv/chroot/rasp-armhf apt-get install --allow-unauthenticated -qq -y $linuxDependencies g++ &&
    sudo mkdir -p /srv/chroot/rasp-armhf/build &&
    sudo rsync -av $TRAVIS_BUILD_DIR/ /srv/chroot/rasp-armhf/build/;
  fi


before_script:
  # download and install android NDK
  - if [ "$BUILD_NAME" == "android" ]; then
      export TERM=dumb &&
      curl -L https://dl.google.com/android/repository/android-ndk-r$USE_ANDROID_NDK_VERSION-linux-x86_64.zip -O &&
      unzip ./android-ndk-r$USE_ANDROID_NDK_VERSION-linux-x86_64.zip > /dev/null &&
      rm android-ndk-r$USE_ANDROID_NDK_VERSION-linux-x86_64.zip &&
      export ANDROID_NDK_HOME=`pwd`/android-ndk-r$USE_ANDROID_NDK_VERSION &&
      export LOCAL_ANDROID_NDK_HOME="$ANDROID_NDK_HOME" &&
      export LOCAL_ANDROID_NDK_HOST_PLATFORM="linux-x86_64" &&
      export PATH=$PATH:${ANDROID_NDK_HOME} &&
      env;
    fi
  - if [ "$BUILD_NAME" == "ios" ]; then
      curl -L https://github.com/zackslash/Xcode-Proj-Adder/raw/master/bin/XcodeProjAdder -O &&
      chmod +x XcodeProjAdder &&
      (cd ios && ../XcodeProjAdder -XCP tests.xcodeproj -SCSV `echo $(find ../src -type f -name *.cpp) | sed -e 's/ /,/g'`);
    fi

script:
- if [ "$BUILD_NAME" == "debian" ]; then
    myci-deb-prepare.sh &&
    sg sbuild -c "sbuild -n -A -d stretch-amd64-sbuild --run-lintian --debbuildopts '-us -uc'";
  fi
- if [ "$BUILD_NAME" == "ubuntu" ]; then
    myci-deb-prepare.sh &&
    sg sbuild -c "sbuild -n -A -d xenial-amd64-sbuild --debbuildopts '-us -uc'";
  fi
- if [ "$BUILD_NAME" == "macosx" ]; then
    make &&
    make test;
  fi
- if [ "$BUILD_NAME" == "ios" ]; then
    xcodebuild -workspace ios/tests.xcworkspace -scheme tests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO;
  fi
- if [ "$BUILD_NAME" == "raspberry_pi" ]; then
    sudo chroot /srv/chroot/rasp-armhf bash -c "cd /build && myci-deb-prepare.sh" &&
    sudo chroot /srv/chroot/rasp-armhf bash -c "cd /build && dpkg-buildpackage -us -uc";
  fi
- if [ "$BUILD_NAME" == "android" ]; then
    (cd android && ./gradlew build) &&
    myci-apply-version.sh -v `myci-deb-version.sh debian/changelog` android/*.pom.in &&
    myci-apply-version.sh -v `myci-deb-version.sh debian/changelog` android/*.aar.in --filename-only;
  fi


before_deploy:
  - myci-apply-version.sh -v `myci-deb-version.sh debian/changelog` travis_bintray_*.json.in

deploy:
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = debian
  file: travis_bintray_deb.json
  user: igagis
  key:
    secure: "cv21gXvPmtFhDaEhIjziH8SAFIxvEWbEdmZxyNEZ75j82i5kwGGZyFaUge+OfHpLDBwrWNVoBB17WUc1lHIu9t/S0AljODHCaN+xQAemNDBVE4krTKHRtkxWhUNa5hY0mGBA+wHsJlWplUDLEIV5sQb4rtw/0ZQttK5/4OXFbQ30uSwgUW2Qvn4RTRRMGRgOGRwiPLtoiX1xjPRL4SBcubF9eyyZNQdrdQQ0SpLTRjMullVqSg9zbYFENKL99CQmrcUgoilC2D7cBgSxI5lTPdEG3fz5wJwj4JroPJ3BA+39WhPXQs682mbqyE887Mp9SJMgA/1V5f1Xh67IXbQs4QpdwYjaGkvX6jfkDKIozVgZ3aeuTkRWDU6cTtIbEbE5Ekq/x/6racuWMS01UwfUFV7cIk7rCT1EbbmkSy3FzezzSlE/Q06Rsqb1zZ5qvIBgjSSnegeDafd77VulqUlGXl5zB5XaazROReLwV6sMBI3dtwPGtT9HHKEGFi1wEMRH9xONEvM9vu6wadS3HT5cq63IkQGfC3r/6jyxDHxcSe4zGPWH+6rdL8SLwaV2VEkDC8JwAFt8q/nWcH2AJ4zdRQw2e1wzT2bAqGPsQ5UbTH5jdMogGEG+CKGdYaQW4xKS+jhg7ScLl7TU7tvVYZXe3YdWV6xbUBzQYlpnXXkugPk="
  dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = ubuntu
  file: travis_bintray_ubu.json
  user: igagis
  key:
    secure: "cv21gXvPmtFhDaEhIjziH8SAFIxvEWbEdmZxyNEZ75j82i5kwGGZyFaUge+OfHpLDBwrWNVoBB17WUc1lHIu9t/S0AljODHCaN+xQAemNDBVE4krTKHRtkxWhUNa5hY0mGBA+wHsJlWplUDLEIV5sQb4rtw/0ZQttK5/4OXFbQ30uSwgUW2Qvn4RTRRMGRgOGRwiPLtoiX1xjPRL4SBcubF9eyyZNQdrdQQ0SpLTRjMullVqSg9zbYFENKL99CQmrcUgoilC2D7cBgSxI5lTPdEG3fz5wJwj4JroPJ3BA+39WhPXQs682mbqyE887Mp9SJMgA/1V5f1Xh67IXbQs4QpdwYjaGkvX6jfkDKIozVgZ3aeuTkRWDU6cTtIbEbE5Ekq/x/6racuWMS01UwfUFV7cIk7rCT1EbbmkSy3FzezzSlE/Q06Rsqb1zZ5qvIBgjSSnegeDafd77VulqUlGXl5zB5XaazROReLwV6sMBI3dtwPGtT9HHKEGFi1wEMRH9xONEvM9vu6wadS3HT5cq63IkQGfC3r/6jyxDHxcSe4zGPWH+6rdL8SLwaV2VEkDC8JwAFt8q/nWcH2AJ4zdRQw2e1wzT2bAqGPsQ5UbTH5jdMogGEG+CKGdYaQW4xKS+jhg7ScLl7TU7tvVYZXe3YdWV6xbUBzQYlpnXXkugPk="
  dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = raspberry_pi
  file: travis_bintray_rasp.json
  user: igagis
  key:
    secure: "cv21gXvPmtFhDaEhIjziH8SAFIxvEWbEdmZxyNEZ75j82i5kwGGZyFaUge+OfHpLDBwrWNVoBB17WUc1lHIu9t/S0AljODHCaN+xQAemNDBVE4krTKHRtkxWhUNa5hY0mGBA+wHsJlWplUDLEIV5sQb4rtw/0ZQttK5/4OXFbQ30uSwgUW2Qvn4RTRRMGRgOGRwiPLtoiX1xjPRL4SBcubF9eyyZNQdrdQQ0SpLTRjMullVqSg9zbYFENKL99CQmrcUgoilC2D7cBgSxI5lTPdEG3fz5wJwj4JroPJ3BA+39WhPXQs682mbqyE887Mp9SJMgA/1V5f1Xh67IXbQs4QpdwYjaGkvX6jfkDKIozVgZ3aeuTkRWDU6cTtIbEbE5Ekq/x/6racuWMS01UwfUFV7cIk7rCT1EbbmkSy3FzezzSlE/Q06Rsqb1zZ5qvIBgjSSnegeDafd77VulqUlGXl5zB5XaazROReLwV6sMBI3dtwPGtT9HHKEGFi1wEMRH9xONEvM9vu6wadS3HT5cq63IkQGfC3r/6jyxDHxcSe4zGPWH+6rdL8SLwaV2VEkDC8JwAFt8q/nWcH2AJ4zdRQw2e1wzT2bAqGPsQ5UbTH5jdMogGEG+CKGdYaQW4xKS+jhg7ScLl7TU7tvVYZXe3YdWV6xbUBzQYlpnXXkugPk="
  dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = android
  file: travis_bintray_android.json
  user: igagis
  key:
    secure: "cv21gXvPmtFhDaEhIjziH8SAFIxvEWbEdmZxyNEZ75j82i5kwGGZyFaUge+OfHpLDBwrWNVoBB17WUc1lHIu9t/S0AljODHCaN+xQAemNDBVE4krTKHRtkxWhUNa5hY0mGBA+wHsJlWplUDLEIV5sQb4rtw/0ZQttK5/4OXFbQ30uSwgUW2Qvn4RTRRMGRgOGRwiPLtoiX1xjPRL4SBcubF9eyyZNQdrdQQ0SpLTRjMullVqSg9zbYFENKL99CQmrcUgoilC2D7cBgSxI5lTPdEG3fz5wJwj4JroPJ3BA+39WhPXQs682mbqyE887Mp9SJMgA/1V5f1Xh67IXbQs4QpdwYjaGkvX6jfkDKIozVgZ3aeuTkRWDU6cTtIbEbE5Ekq/x/6racuWMS01UwfUFV7cIk7rCT1EbbmkSy3FzezzSlE/Q06Rsqb1zZ5qvIBgjSSnegeDafd77VulqUlGXl5zB5XaazROReLwV6sMBI3dtwPGtT9HHKEGFi1wEMRH9xONEvM9vu6wadS3HT5cq63IkQGfC3r/6jyxDHxcSe4zGPWH+6rdL8SLwaV2VEkDC8JwAFt8q/nWcH2AJ4zdRQw2e1wzT2bAqGPsQ5UbTH5jdMogGEG+CKGdYaQW4xKS+jhg7ScLl7TU7tvVYZXe3YdWV6xbUBzQYlpnXXkugPk="
  dry-run: false
- provider: script
  skip_cleanup: true
  script: myci-deploy-homebrew.sh -t igagis/tap
  on:
    tags: true
    condition: $BUILD_NAME = macosx
- provider: script
  skip_cleanup: true
  script: rvm 2.3.3 do myci-deploy-cocoapods.sh -r igagis
  on:
    tags: true
    condition: $BUILD_NAME = ios
