branches:
  except:
  - release

sudo: required

matrix:
  include:
    - os: osx
      env: BUILD_NAME=macosx
      compiler: clang
      language: cpp
      osx_image: xcode7.3
    - os: osx
      env: BUILD_NAME=ios
      compiler: clang
      language: cpp
      osx_image: xcode7.3
    - os: linux
      env: BUILD_NAME=debian
      compiler: gcc
      language: cpp
      dist: trusty
    - os: linux
      env: BUILD_NAME=ubuntu
      compiler: gcc
      language: cpp
      dist: trusty
    - os: linux
      env: BUILD_NAME=raspberry_pi
      compiler: gcc
      language: cpp
      dist: trusty
    - env: BUILD_NAME=android
      language: android


android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
#    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository


env:
  global:
  #encrypted HOMEBREW_GITHUB_ACCESS_TOKEN for publishing to homebrew-tap
  - secure: "y+Nuee9K4ysuIXcsU0B4Vf5KxNEwPiKmTWUWKJKhIfyINid+9OYoFQqtK54vqkyKIpngluXbWF5tV0fYuAsG4zWOQ2KNIVgEDO+3GgRltnjIdUz1YnkwHowzWswx6sfnI3QBWIsitNwa51Wouh0zwfZDOeD18NMlcpAYobUzSeK+mwDKtcLM63EqyuhJaWyj0Pc9a/IMzMVaIKE73GQM6Tx2d2c8W/6yJwP/fAV4jR/9BmD2o3TMlJtvEaZ3n0Q9sA/kutCTOspQToHqii8etGX70I67I1wVz2gjiXhh48N1Bmc4o2xFbKSi9106+RH7fuzaA5rj+JNlwr3RffJ9ggSS9v8FcH13NzWkPKL9Ovxfyr87ntVJhd9oRcz/EmyuY9D7IyH3GuZ5YLwfN3Q8JIsO+gQeLo4j2wyF1F0mdm5S9s9QLIJt2jmeX+Uw8blRubyfZlHPmUiJQqprTooHTvIeuHqjcPTLkaYQZv8jaZwI7kHFfOD1R8MxofekWiKvhpUXQHAyln6LZ59aqtPDTj4tEQ+kEiCNcVTnt0CczlI71BiO8VKRDjxsys0yV7Am1M/ur35rw50gEblqqMVO/fwdneEGjOlmJ/6Frn8uhuKpEThZdKXTiiQataWOnQ0DLLnBlhtXjdfc9DWbrH7c8UcrFu+R746XL7QkTyAO2AE="
  - PRORAB_GIT_USERNAME=igagis
  - PRORAB_GIT_ACCESS_TOKEN=$HOMEBREW_GITHUB_ACCESS_TOKEN
  - USE_ANDROID_NDK_VERSION=15c
  - linuxDependencies="lintian debhelper prorab doxygen libutki-dev libpapki-dev"


before_install:
- if [ "$BUILD_NAME" == "macosx" ]; then
    brew tap igagis/tap &&
    brew update > /dev/null &&
    brew install prorab libutki libpapki;
  fi
- if [ "$BUILD_NAME" == "ios" ]; then
    brew tap igagis/tap &&
    brew update > /dev/null &&
    brew install prorab &&

    brew install --force openssl &&
    rvm install ruby-2.2.2 &&
    rvm use ruby-2.2.2 &&
    
    rvm 2.2.1 do gem uninstall bundler -v '>1.12.5' --force &&
    rvm 2.2.1 do gem install bundler -v 1.12.5 --no-rdoc --no-ri --no-document --quiet &&
    
    sudo gem install cocoapods &&
    pod repo add --silent igagis https://$PRORAB_GIT_USERNAME:$PRORAB_GIT_ACCESS_TOKEN@github.com/igagis/cocoapods-repo.git &&
    pod install --project-directory=ios;
  fi
- if [ "$BUILD_NAME" == "android" ]; then
    echo "deb [arch=amd64] https://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq prorab;
  fi
- if [ "$BUILD_NAME" == "debian" ]; then
    echo "deb [arch=amd64] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq sbuild prorab debhelper &&
    sudo sbuild-adduser $LOGNAME &&
    echo lQHYBFfZDkYBBACyRm0LCwK/9rSzqSJyEBihVNA61meWp9MVjn3EBPp6MV1/mjZ80LPJ6ecYX6VMu861a5yQLnlA9krUxuHxjnsEYvMQiz0zHapp8Zqu0FIvcU1IWZV7Eio5Lej7QFeHFmtPlrSqT152lVUmQFW9ZCtWOOM1KnKBhoWWLf9z7LnwSwARAQABAAP/SWyYHKQ8TbPeWOCgPzpB6rBz0sfbgkE8vvQg+ErUnt8WEygAqQeMBO1BMNizzBbN3AqmQPvjFM5bo6cGB+cW4tbmWVtp8wMGVm8dobiZP3p1YLtvrweX3gYo1P4km8B7JkeJ0oyGa1k4yP5m4+o7t97EanKLFTFCbJvV/txT+YECAMLhKBMGJBqa8766tsyXbKaHQKvUDwlVCltAbeRb/V7cnIEuf/bn5DcN2O3yhN35OX5EvCeJxtCSBDh9HkQfK0cCAOowGoepffgLuuOfnpNU3GcHU9lNsLUnYJ17Oa38z1JGjggrUvQ5V6UbH0YY14vQXbrOVn+YE9Job9UCnM6DzN0B/19ZoYzH9anOf+nmTM56Rrk8itQXhN/gpI22EZ9n8koELvYrHj3iUgPJ+BOCKTP3E9brojEC048pK58GFJkr+/qjqbRgU2J1aWxkIFNpZ25lciAoU2J1aWxkIEJ1aWxkIERlcGVuZGVuY3kgQXJjaGl2ZSBLZXkpIDxidWlsZGQtdG9vbHMtZGV2ZWxAbGlzdHMuYWxpb3RoLmRlYmlhbi5vcmc+iLgEEwECACIFAlfZDkYCGy8GCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJELG4iKvjYvQgomAEAJzhmqIVxIU3+ROL0B8Q2Iv1gWRe6X17J1UQPYIGkRYcZWYUllWjmk32snT5Yv+x2TMVojD0JCCgltU0JBvydovItd+g6H+C8I/bhoq5twC9CIYGKmhDInxwCdHG8yU7AVdEopf38VsEC+3Hazh4V5sPldHMo9Lx6u5uXiil5qKi | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.sec > /dev/null &&
    echo mI0EV9kORgEEALJGbQsLAr/2tLOpInIQGKFU0DrWZ5an0xWOfcQE+noxXX+aNnzQs8np5xhfpUy7zrVrnJAueUD2StTG4fGOewRi8xCLPTMdqmnxmq7QUi9xTUhZlXsSKjkt6PtAV4cWa0+WtKpPXnaVVSZAVb1kK1Y44zUqcoGGhZYt/3PsufBLABEBAAG0YFNidWlsZCBTaWduZXIgKFNidWlsZCBCdWlsZCBEZXBlbmRlbmN5IEFyY2hpdmUgS2V5KSA8YnVpbGRkLXRvb2xzLWRldmVsQGxpc3RzLmFsaW90aC5kZWJpYW4ub3JnPoi4BBMBAgAiBQJX2Q5GAhsvBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRCxuIir42L0IKJgBACc4ZqiFcSFN/kTi9AfENiL9YFkXul9eydVED2CBpEWHGVmFJZVo5pN9rJ0+WL/sdkzFaIw9CQgoJbVNCQb8naLyLXfoOh/gvCP24aKubcAvQiGBipoQyJ8cAnRxvMlOwFXRKKX9/FbBAvtx2s4eFebD5XRzKPS8erubl4opeaiog== | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.pub > /dev/null &&
    sudo sbuild-createchroot --include=gnupg1,dirmngr,build-essential testing /srv/chroot/deb-amd64 http://httpredir.debian.org/debian &&
    echo "deb [trusted=yes] http://dl.bintray.com/igagis/deb unstable main" | sudo tee /srv/chroot/deb-amd64/etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo chroot /srv/chroot/deb-amd64 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo chroot /srv/chroot/deb-amd64 ln -s /usr/bin/gpg1 /usr/bin/gpg;
  fi
- if [ "$BUILD_NAME" == "ubuntu" ]; then
    echo "deb [arch=amd64] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq sbuild prorab debhelper &&
    sudo sbuild-adduser $LOGNAME &&
    echo lQHYBFfZDkYBBACyRm0LCwK/9rSzqSJyEBihVNA61meWp9MVjn3EBPp6MV1/mjZ80LPJ6ecYX6VMu861a5yQLnlA9krUxuHxjnsEYvMQiz0zHapp8Zqu0FIvcU1IWZV7Eio5Lej7QFeHFmtPlrSqT152lVUmQFW9ZCtWOOM1KnKBhoWWLf9z7LnwSwARAQABAAP/SWyYHKQ8TbPeWOCgPzpB6rBz0sfbgkE8vvQg+ErUnt8WEygAqQeMBO1BMNizzBbN3AqmQPvjFM5bo6cGB+cW4tbmWVtp8wMGVm8dobiZP3p1YLtvrweX3gYo1P4km8B7JkeJ0oyGa1k4yP5m4+o7t97EanKLFTFCbJvV/txT+YECAMLhKBMGJBqa8766tsyXbKaHQKvUDwlVCltAbeRb/V7cnIEuf/bn5DcN2O3yhN35OX5EvCeJxtCSBDh9HkQfK0cCAOowGoepffgLuuOfnpNU3GcHU9lNsLUnYJ17Oa38z1JGjggrUvQ5V6UbH0YY14vQXbrOVn+YE9Job9UCnM6DzN0B/19ZoYzH9anOf+nmTM56Rrk8itQXhN/gpI22EZ9n8koELvYrHj3iUgPJ+BOCKTP3E9brojEC048pK58GFJkr+/qjqbRgU2J1aWxkIFNpZ25lciAoU2J1aWxkIEJ1aWxkIERlcGVuZGVuY3kgQXJjaGl2ZSBLZXkpIDxidWlsZGQtdG9vbHMtZGV2ZWxAbGlzdHMuYWxpb3RoLmRlYmlhbi5vcmc+iLgEEwECACIFAlfZDkYCGy8GCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJELG4iKvjYvQgomAEAJzhmqIVxIU3+ROL0B8Q2Iv1gWRe6X17J1UQPYIGkRYcZWYUllWjmk32snT5Yv+x2TMVojD0JCCgltU0JBvydovItd+g6H+C8I/bhoq5twC9CIYGKmhDInxwCdHG8yU7AVdEopf38VsEC+3Hazh4V5sPldHMo9Lx6u5uXiil5qKi | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.sec > /dev/null &&
    echo mI0EV9kORgEEALJGbQsLAr/2tLOpInIQGKFU0DrWZ5an0xWOfcQE+noxXX+aNnzQs8np5xhfpUy7zrVrnJAueUD2StTG4fGOewRi8xCLPTMdqmnxmq7QUi9xTUhZlXsSKjkt6PtAV4cWa0+WtKpPXnaVVSZAVb1kK1Y44zUqcoGGhZYt/3PsufBLABEBAAG0YFNidWlsZCBTaWduZXIgKFNidWlsZCBCdWlsZCBEZXBlbmRlbmN5IEFyY2hpdmUgS2V5KSA8YnVpbGRkLXRvb2xzLWRldmVsQGxpc3RzLmFsaW90aC5kZWJpYW4ub3JnPoi4BBMBAgAiBQJX2Q5GAhsvBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRCxuIir42L0IKJgBACc4ZqiFcSFN/kTi9AfENiL9YFkXul9eydVED2CBpEWHGVmFJZVo5pN9rJ0+WL/sdkzFaIw9CQgoJbVNCQb8naLyLXfoOh/gvCP24aKubcAvQiGBipoQyJ8cAnRxvMlOwFXRKKX9/FbBAvtx2s4eFebD5XRzKPS8erubl4opeaiog== | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.pub > /dev/null &&
    sudo sbuild-createchroot --include=gnupg,dirmngr,build-essential --components=main,universe xenial /srv/chroot/ubu-amd64 http://archive.ubuntu.com/ubuntu/ &&
    echo "deb [trusted=yes] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /srv/chroot/ubu-amd64/etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo chroot /srv/chroot/ubu-amd64 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61;
  fi
- if [ "$BUILD_NAME" == "raspberry_pi" ]; then
    echo "deb [arch=amd64] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq prorab;
    sudo prorab-make-raspberry-chroot.sh /srv/chroot/rasp-armhf &&
    echo "deb [arch=armhf] http://dl.bintray.com/igagis/rasp unstable main" | sudo tee /srv/chroot/rasp-armhf/etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo chroot /srv/chroot/rasp-armhf apt-get update &&
    sudo chroot /srv/chroot/rasp-armhf apt-get install --allow-unauthenticated -qq -y $linuxDependencies g++ &&
    sudo mkdir -p /srv/chroot/rasp-armhf/build &&
    sudo rsync -av $TRAVIS_BUILD_DIR/ /srv/chroot/rasp-armhf/build/;
  fi


before_script:
  # download and install android NDK
  - if [ "$BUILD_NAME" == "android" ]; then
      export TERM=dumb &&
      curl -L https://dl.google.com/android/repository/android-ndk-r$USE_ANDROID_NDK_VERSION-linux-x86_64.zip -O &&
      unzip ./android-ndk-r$USE_ANDROID_NDK_VERSION-linux-x86_64.zip > /dev/null &&
      rm android-ndk-r$USE_ANDROID_NDK_VERSION-linux-x86_64.zip &&
      export ANDROID_NDK_HOME=`pwd`/android-ndk-r$USE_ANDROID_NDK_VERSION &&
      export LOCAL_ANDROID_NDK_HOME="$ANDROID_NDK_HOME" &&
      export LOCAL_ANDROID_NDK_HOST_PLATFORM="linux-x86_64" &&
      export PATH=$PATH:${ANDROID_NDK_HOME} &&
      env;
    fi
  - if [ "$BUILD_NAME" == "ios" ]; then
      curl -L https://github.com/zackslash/Xcode-Proj-Adder/raw/master/bin/XcodeProjAdder -O &&
      chmod +x XcodeProjAdder &&
      (cd ios && ../XcodeProjAdder -XCP tests.xcodeproj -SCSV `echo $(find ../src -type f -name *.cpp) | sed -n -e 's/ /,/gp'`);
    fi

script:
- if [ "$BUILD_NAME" == "debian" ]; then
    prorab-deb-prepare.sh &&
    sg sbuild -c "sbuild -n -A -d testing-amd64-sbuild --run-lintian --debbuildopts '-us -uc'";
  fi
- if [ "$BUILD_NAME" == "ubuntu" ]; then
    prorab-deb-prepare.sh &&
    sg sbuild -c "sbuild -n -A -d xenial-amd64-sbuild --debbuildopts '-us -uc'";
  fi
- if [ "$BUILD_NAME" == "macosx" ]; then
    make &&
    make test;
  fi
- if [ "$BUILD_NAME" == "ios" ]; then
    xcodebuild -workspace ios/tests.xcworkspace -scheme tests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO;
  fi
- if [ "$BUILD_NAME" == "raspberry_pi" ]; then
    sudo chroot /srv/chroot/rasp-armhf bash -c "cd /build && prorab-deb-prepare.sh" &&
    sudo chroot /srv/chroot/rasp-armhf bash -c "cd /build && dpkg-buildpackage -us -uc";
  fi
- if [ "$BUILD_NAME" == "android" ]; then
    (cd android && ./gradlew build) &&
    prorab-apply-version.sh -v `prorab-deb-version.sh debian/changelog` android/*.pom.in &&
    prorab-apply-version.sh -v `prorab-deb-version.sh debian/changelog` android/*.aar.in --filename-only;
  fi


before_deploy:
  - prorab-apply-version.sh -v `prorab-deb-version.sh debian/changelog` travis_bintray_*.json.in

deploy:
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = debian
  file: travis_bintray_deb.json
  user: igagis
  key:
    secure: "Ov0P7ufWG1YR3MSwjqPCveKHyz1qr1kGewuwe/U0ASIORMRxek9T0BBW0X6MDMsLlgCc20OkmhNc05EfOA6w6TRFICizvZAls0P6mpXN/8UO0VUUiJGoL/SlnyV3GcuoTOOpGUjy4SBIFEgSW8vLMCwRz2fi7UmirHB9zEDN3KkUyQ0a1kDjBmesxr1UdQpni80yhc3nePXT/o49zLtmHcV4TtG95sxsANt3z/2WYsHiF0R46tg9AVaOlujLR3Xjm0oZRYJpcyPAKVJTADJ1ili2vcycndYLqy8wWrFacyA+59arYtN6P/8KiuUm6TPVOTSPL0M50hWpsQb7+CYgUwm5qop+vpGNPr9WHpI1SEh9DRyNNaceUlsMUdHEWvszsNA+AdvNZvc3hxE6Hsdsd0RRzpTclRYXMG911EYGxE6k1bFZufIpM6iwv0QmLo9kzeCf0GcVEdvg00OQLDveZHGDa57uliFmXnGQfRKVaU+0HAkHF9LTVjs+ve5vTpMLQtI8eLRBBpwcME6Bke3stMgKVAJk4cr9AomKDR75SeFfWB+oCkRkkyZ9H+BPv5XaZk3zJBzw75PUdRNiAzS3d8t0yO35LCZNpgJX3biFzPZfDW6t2ixsA02Z7LoZZasPZRyXeMK8WdyCCrg1xvRJvWlfdMBzHi/nTWD6KGhNFhA="
  dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = ubuntu
  file: travis_bintray_ubu.json
  user: igagis
  key:
    secure: "Ov0P7ufWG1YR3MSwjqPCveKHyz1qr1kGewuwe/U0ASIORMRxek9T0BBW0X6MDMsLlgCc20OkmhNc05EfOA6w6TRFICizvZAls0P6mpXN/8UO0VUUiJGoL/SlnyV3GcuoTOOpGUjy4SBIFEgSW8vLMCwRz2fi7UmirHB9zEDN3KkUyQ0a1kDjBmesxr1UdQpni80yhc3nePXT/o49zLtmHcV4TtG95sxsANt3z/2WYsHiF0R46tg9AVaOlujLR3Xjm0oZRYJpcyPAKVJTADJ1ili2vcycndYLqy8wWrFacyA+59arYtN6P/8KiuUm6TPVOTSPL0M50hWpsQb7+CYgUwm5qop+vpGNPr9WHpI1SEh9DRyNNaceUlsMUdHEWvszsNA+AdvNZvc3hxE6Hsdsd0RRzpTclRYXMG911EYGxE6k1bFZufIpM6iwv0QmLo9kzeCf0GcVEdvg00OQLDveZHGDa57uliFmXnGQfRKVaU+0HAkHF9LTVjs+ve5vTpMLQtI8eLRBBpwcME6Bke3stMgKVAJk4cr9AomKDR75SeFfWB+oCkRkkyZ9H+BPv5XaZk3zJBzw75PUdRNiAzS3d8t0yO35LCZNpgJX3biFzPZfDW6t2ixsA02Z7LoZZasPZRyXeMK8WdyCCrg1xvRJvWlfdMBzHi/nTWD6KGhNFhA="
  dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = raspberry_pi
  file: travis_bintray_rasp.json
  user: igagis
  key:
    secure: "Ov0P7ufWG1YR3MSwjqPCveKHyz1qr1kGewuwe/U0ASIORMRxek9T0BBW0X6MDMsLlgCc20OkmhNc05EfOA6w6TRFICizvZAls0P6mpXN/8UO0VUUiJGoL/SlnyV3GcuoTOOpGUjy4SBIFEgSW8vLMCwRz2fi7UmirHB9zEDN3KkUyQ0a1kDjBmesxr1UdQpni80yhc3nePXT/o49zLtmHcV4TtG95sxsANt3z/2WYsHiF0R46tg9AVaOlujLR3Xjm0oZRYJpcyPAKVJTADJ1ili2vcycndYLqy8wWrFacyA+59arYtN6P/8KiuUm6TPVOTSPL0M50hWpsQb7+CYgUwm5qop+vpGNPr9WHpI1SEh9DRyNNaceUlsMUdHEWvszsNA+AdvNZvc3hxE6Hsdsd0RRzpTclRYXMG911EYGxE6k1bFZufIpM6iwv0QmLo9kzeCf0GcVEdvg00OQLDveZHGDa57uliFmXnGQfRKVaU+0HAkHF9LTVjs+ve5vTpMLQtI8eLRBBpwcME6Bke3stMgKVAJk4cr9AomKDR75SeFfWB+oCkRkkyZ9H+BPv5XaZk3zJBzw75PUdRNiAzS3d8t0yO35LCZNpgJX3biFzPZfDW6t2ixsA02Z7LoZZasPZRyXeMK8WdyCCrg1xvRJvWlfdMBzHi/nTWD6KGhNFhA="
  dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = android
  file: travis_bintray_android.json
  user: igagis
  key:
    secure: "Ov0P7ufWG1YR3MSwjqPCveKHyz1qr1kGewuwe/U0ASIORMRxek9T0BBW0X6MDMsLlgCc20OkmhNc05EfOA6w6TRFICizvZAls0P6mpXN/8UO0VUUiJGoL/SlnyV3GcuoTOOpGUjy4SBIFEgSW8vLMCwRz2fi7UmirHB9zEDN3KkUyQ0a1kDjBmesxr1UdQpni80yhc3nePXT/o49zLtmHcV4TtG95sxsANt3z/2WYsHiF0R46tg9AVaOlujLR3Xjm0oZRYJpcyPAKVJTADJ1ili2vcycndYLqy8wWrFacyA+59arYtN6P/8KiuUm6TPVOTSPL0M50hWpsQb7+CYgUwm5qop+vpGNPr9WHpI1SEh9DRyNNaceUlsMUdHEWvszsNA+AdvNZvc3hxE6Hsdsd0RRzpTclRYXMG911EYGxE6k1bFZufIpM6iwv0QmLo9kzeCf0GcVEdvg00OQLDveZHGDa57uliFmXnGQfRKVaU+0HAkHF9LTVjs+ve5vTpMLQtI8eLRBBpwcME6Bke3stMgKVAJk4cr9AomKDR75SeFfWB+oCkRkkyZ9H+BPv5XaZk3zJBzw75PUdRNiAzS3d8t0yO35LCZNpgJX3biFzPZfDW6t2ixsA02Z7LoZZasPZRyXeMK8WdyCCrg1xvRJvWlfdMBzHi/nTWD6KGhNFhA="
  dry-run: false
- provider: script
  skip_cleanup: true
  script: prorab-deploy-homebrew.sh -t igagis/tap
  on:
    tags: true
    condition: $BUILD_NAME = macosx
- provider: script
  skip_cleanup: true
  script: rvm 2.2.1 do prorab-deploy-cocoapods.sh -r igagis
  on:
    tags: true
    condition: $BUILD_NAME = ios
